### ISSUE TITLE
Problems when used in install profile

### ISSUE THREAD

**Issue by Ishino** [kristofvanroy/nice-dash#2]
When installing the nice dash from an install profile, some problems occur when using batches in the profile. At some point nice dash redirects to the dashboard. This breaks the running batch and you end up with a half run install.

Nice dash checks if in the init if the redirect is set true after logging in. During the install you are logged in as admin, and the custom tasks are run after. The init prevents the tasks to run and so the install brakes.

A quick for us was to check in the init the install_task variable. And only redirect when its set to 'done'. A better solution would be that this feature (redirect after login) was configurable and set false by default. The admin could set this to true after the install. In the configuration pages.

Maybe it could become so that the dashboard is the default page when going to /admin , again configurable.

grts and thanks for this useful module!

Ishino

**Comment by kristofvanroy** [comment]
This is fixed and will be released in V2 branch. Thanks for your valuable feedback!
